/**
 * App shell navigation CTA event surface.
 */
export {
  APP_SHELL_SURFACE,
  appShellCategoryAnalyticsData,
  appShellCategoryAnalyticsEvent,
  appShellCategoryDestination,
  appShellFeedChipAnalyticsData,
  appShellFeedChipAnalyticsEvent,
  appShellFeedChipHrefDestination,
  appShellFooterLinkAnalyticsData,
  appShellFooterLinkAnalyticsEvent,
  appShellHeaderAnalyticsData,
  appShellHeaderAnalyticsEvent,
  appShellHeaderSubmitDestination,
  appShellLegalAnalyticsData,
  appShellLegalAnalyticsEvent,
  appShellLegalRouteDestination,
  appShellNavAnalyticsData,
  appShellNavAnalyticsEvent,
  appShellNavRouteDestination,
  type AppShellCategoryDestination,
  type AppShellFeedChip,
  type AppShellFeedChipHrefDestination,
  type AppShellHeaderAction,
  type AppShellHeaderSubmitDestination,
  type AppShellLegalDestination,
  type AppShellLegalRouteDestination,
  type AppShellNavRouteDestination,
  type AppShellNavSource,
} from "@/lib/app-shell-cta-events-lib";
