/**
 * Directory hub navigation CTA event surface.
 */
export {
  BEST_INDEX_SURFACE,
  CATEGORY_HUB_NOTFOUND_SURFACE,
  CATEGORY_HUB_SURFACE,
  PLATFORM_CATEGORY_NOTFOUND_SURFACE,
  PLATFORM_CATEGORY_SURFACE,
  PLATFORM_HUB_NOTFOUND_SURFACE,
  PLATFORM_HUB_SURFACE,
  PLATFORM_INDEX_SURFACE,
  bestIndexListAnalyticsData,
  bestIndexListAnalyticsEvent,
  bestIndexListDestination,
  categoryHubBrowseAnalyticsData,
  categoryHubBrowseAnalyticsEvent,
  categoryHubBrowseDestination,
  categoryHubNotFoundEgressAnalyticsData,
  categoryHubNotFoundEgressAnalyticsEvent,
  categoryHubNotFoundEgressDestination,
  categoryHubSeeAllAnalyticsData,
  categoryHubSeeAllAnalyticsEvent,
  categoryHubSeeAllDestination,
  platformCategoryCategoryAnalyticsData,
  platformCategoryCategoryAnalyticsEvent,
  platformCategoryCategoryDestination,
  platformCategoryNotFoundEgressAnalyticsData,
  platformCategoryNotFoundEgressAnalyticsEvent,
  platformCategoryNotFoundEgressDestination,
  platformCategoryPlatformAnalyticsData,
  platformCategoryPlatformAnalyticsEvent,
  platformCategoryPlatformDestination,
  platformHubBrowseAnalyticsData,
  platformHubBrowseAnalyticsEvent,
  platformHubBrowseDestination,
  platformHubNotFoundEgressAnalyticsData,
  platformHubNotFoundEgressAnalyticsEvent,
  platformHubNotFoundEgressDestination,
  platformHubSectionAnalyticsData,
  platformHubSectionAnalyticsEvent,
  platformHubSectionDestination,
  platformIndexSelectAnalyticsData,
  platformIndexSelectAnalyticsEvent,
  platformIndexSelectDestination,
  type BestIndexListDestination,
  type CategoryHubBrowseDestination,
  type CategoryHubNotFoundEgressDestination,
  type CategoryHubSeeAllDestination,
  type PlatformCategoryCategoryDestination,
  type PlatformCategoryNotFoundEgressDestination,
  type PlatformCategoryPlatformDestination,
  type PlatformHubBrowseDestination,
  type PlatformHubNotFoundEgressDestination,
  type PlatformHubSectionDestination,
  type PlatformIndexSelectDestination,
} from "@/lib/directory-hub-cta-events-lib";
