/**
 * Ecosystem page navigation CTA event surface.
 */
export {
  ECOSYSTEM_PAGE_SURFACE,
  ecosystemApiDocsAnalyticsData,
  ecosystemApiDocsAnalyticsEvent,
  ecosystemHarnessBrowseAnalyticsData,
  ecosystemHarnessBrowseAnalyticsEvent,
  ecosystemIntegrationCardAnalyticsData,
  ecosystemIntegrationCardAnalyticsEvent,
  ecosystemKindFilterAnalyticsData,
  ecosystemKindFilterAnalyticsEvent,
  ecosystemMatrixCellAnalyticsData,
  ecosystemMatrixCellAnalyticsEvent,
  ecosystemMatrixClientFocusAnalyticsData,
  ecosystemMatrixClientFocusAnalyticsEvent,
  ecosystemMatrixCsvAnalyticsData,
  ecosystemMatrixCsvAnalyticsEvent,
  ecosystemMatrixDocAnalyticsData,
  ecosystemMatrixDocAnalyticsEvent,
  ecosystemMatrixFocusClearAnalyticsData,
  ecosystemMatrixFocusClearAnalyticsEvent,
  ecosystemMatrixSnippetCopyAnalyticsData,
  ecosystemMatrixSnippetCopyAnalyticsEvent,
  ecosystemMatrixSupportFocusAnalyticsData,
  ecosystemMatrixSupportFocusAnalyticsEvent,
  ecosystemSectionAnalyticsData,
  ecosystemSectionAnalyticsEvent,
  ecosystemSetupClientAnalyticsData,
  ecosystemSetupClientAnalyticsEvent,
  ecosystemSetupDocAnalyticsData,
  ecosystemSetupDocAnalyticsEvent,
  ecosystemFeedPathAnalyticsData,
  ecosystemFeedPathAnalyticsEvent,
  ecosystemFeedKey,
  ecosystemFeedUrlCopyAnalyticsData,
  ecosystemFeedUrlCopyAnalyticsEvent,
  ecosystemQuickStartCopyAnalyticsData,
  ecosystemQuickStartCopyAnalyticsEvent,
  ecosystemPageStatAnalyticsData,
  ecosystemPageStatAnalyticsEvent,
  ecosystemPageStatDestination,
  type EcosystemMatrixSupport,
  type EcosystemPageStatId,
  type EcosystemQuickStartAction,
  type EcosystemSetupDocDestination,
  type EcosystemSetupSurface,
} from "@/lib/ecosystem-page-cta-events-lib";
