/**
 * Home page navigation CTA event surface.
 */
export {
  HOME_PAGE_SURFACE,
  homeBriefAnalyticsData,
  homeBriefAnalyticsEvent,
  homeCategorySelectAnalyticsData,
  homeCategorySelectAnalyticsEvent,
  homeCompareRailCtaAnalyticsData,
  homeCompareRailCtaAnalyticsEvent,
  homeContributeCtaAnalyticsData,
  homeContributeCtaAnalyticsEvent,
  homeHeroCtaAnalyticsData,
  homeHeroCtaAnalyticsEvent,
  homeHeroExampleSearchAnalyticsData,
  homeHeroExampleSearchAnalyticsEvent,
  homeIntentSelectAnalyticsData,
  homeIntentSelectAnalyticsEvent,
  homePopularSearchAnalyticsData,
  homePopularSearchAnalyticsEvent,
  homePulseChangelogEgressAnalyticsData,
  homePulseChangelogEgressAnalyticsEvent,
  homePulseChangelogRowAnalyticsData,
  homePulseChangelogRowAnalyticsEvent,
  homePulseContributorClickAnalyticsData,
  homePulseContributorClickAnalyticsEvent,
  homePulseContributorsIndexAnalyticsData,
  homePulseContributorsIndexAnalyticsEvent,
  homeRailCtaAnalyticsData,
  homeRailCtaAnalyticsEvent,
  homeTrustStatAnalyticsData,
  homeTrustStatAnalyticsEvent,
  type HomeCompareRailCtaId,
  type HomeContributeCtaId,
  type HomeHeroCtaId,
  type HomeTrustStatId,
} from "@/lib/home-page-cta-events-lib";
